# Site settings
title: GuillimCoin
email: guillimcoin@guigloo.33mail.com
url: https://guillim.github.io/guillimcoin
description: "The Guillim Coin website"
keywords: "cryptocurrency, gui, guillim, coin, guillimcoin, crypto, Binance, wallet, blockchain"
skills: "The other currency"
descriptioncrypto: "Open source peer-to-peer digital currency"
meta_author: guillim

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffffff #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 02aee4 #FD6E8A
  secondary-dark: 233140 #A2122F
  font-primary: 02aee4

# Footer settings
footer:
  copyright: Guillim
  credits: Credits



# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

baseurl: "/guillimcoin"
